name: Update Football Data

on:
  schedule:
    # Runs daily at 6:00 AM UTC (before European matches start)
    - cron: '0 6 * * *'
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: |
          cd scripts
          npm install cheerio node-fetch@2
          
      - name: Run scraper
        run: node scripts/scrape-data.js
        
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add public/data/*.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update football data - $(date +'%Y-%m-%d')" && git push)
